# Generated by Django 2.1.3 on 2018-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('type', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('voltage', models.IntegerField(blank=True, default=120)),
                ('amperage', models.IntegerField(blank=True, default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('type', models.CharField(max_length=128)),
                ('rate', models.IntegerField(blank=True)),
                ('description', models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
