# Generated by Django 2.1.3 on 2018-11-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_waypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='type',
        ),
    ]
