# Generated by Django 2.1.3 on 2018-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_remove_hotel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
