# Generated by Django 2.1.3 on 2018-11-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20181117_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lon',
            field=models.FloatField(),
        ),
    ]
